version: '3.8'

services:

  api:
    build:
      context: . 
      dockerfile: Dockerfile 
    volumes:
      - .:/usr/src/app 
    ports: 
      - 5004:5000
    environment:
      - FLASK_APP=src/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=src.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@api-db:5432/api_dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@api-db:5432/api_test
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on: 
      - api-db 
    
  api-db: 
    build:  
      context: ./src/database 
      dockerfile: Dockerfile 
    ports: 
      - 5432:5432
    environment: 
      - FLASK_APP=src/__init__.py
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  worker: 
    build: .
    command: celery -A src.celery worker --loglevel=info
    volumes: 
      - .:/usr/src/app 
    environment:
      - FLASK_APP=src/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=src.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@api-db:5432/api_dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@api-db:5432/api_test
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - api
      - api-db
      - redis

  redis: 
    image: redis:6-alpine
    restart: always
    expose:
      - 6379
    ports:
      - 6379:6379