"""Inital migration

Revision ID: 18787fdb2283
Revises: 
Create Date: 2022-01-22 19:19:45.394733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18787fdb2283'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('modelname', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model')
    # ### end Alembic commands ###
