"""Adding new columns.

Revision ID: 4374e0117970
Revises: 18787fdb2283
Create Date: 2022-01-22 22:14:00.260401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4374e0117970'
down_revision = '18787fdb2283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('precision', sa.Float(), nullable=False))
    op.add_column('model', sa.Column('recall', sa.Float(), nullable=False))
    op.add_column('model', sa.Column('accuracy', sa.Float(), nullable=False))
    op.add_column('model', sa.Column('auc', sa.Float(), nullable=False))
    op.add_column('model', sa.Column('f1', sa.Float(), nullable=False))
    op.add_column('model', sa.Column('time', sa.Float(), nullable=False))
    op.add_column('model', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('model', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_model_created_at'), 'model', ['created_at'], unique=False)
    op.create_unique_constraint(None, 'model', ['modelname'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'model', type_='unique')
    op.drop_index(op.f('ix_model_created_at'), table_name='model')
    op.drop_column('model', 'updated_at')
    op.drop_column('model', 'created_at')
    op.drop_column('model', 'time')
    op.drop_column('model', 'f1')
    op.drop_column('model', 'auc')
    op.drop_column('model', 'accuracy')
    op.drop_column('model', 'recall')
    op.drop_column('model', 'precision')
    # ### end Alembic commands ###
