"""Adding relationship table.

Revision ID: b262a47d9a73
Revises: 4374e0117970
Create Date: 2022-01-22 22:38:38.426274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b262a47d9a73'
down_revision = '4374e0117970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predict',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction', sa.JSON(), nullable=False),
    sa.Column('prediction', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predict_created_at'), 'predict', ['created_at'], unique=False)
    op.create_index(op.f('ix_predict_updated_at'), 'predict', ['updated_at'], unique=False)
    op.add_column('model', sa.Column('enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model', 'enabled')
    op.drop_index(op.f('ix_predict_updated_at'), table_name='predict')
    op.drop_index(op.f('ix_predict_created_at'), table_name='predict')
    op.drop_table('predict')
    # ### end Alembic commands ###
